src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\Column]
    private ?string $ref = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?bool $published = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\ManyToOne(inversedBy: 'Books')]
    private ?Author $author = null;

    #[ORM\Column(length: 255)]
    private ?string $category = null;

    public function getref(): ?string
    {
        return $this->ref;
    }

    public function setref(string $ref): static
    {
        $this->ref = $ref;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): static
    {
        $this->published = $published;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ref')
            ->add('title')
            ->add('published')
            ->add('publication_date')
            ->add('category')
            ->add('author')
            ->add('envoyer',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use App\Entity\Book;
use App\Form\BookType;
use App\Repository\BookRepository;
use Doctrine\ORM\Repository\RepositoryFactory;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookController extends AbstractController
{
    #[Route('/book', name: 'app_book')]
    public function index(): Response
    {
        return $this->render('book/index.html.twig', [
            'controller_name' => 'BookController',
        ]);
    }

    #[Route('/addBook', name: 'addBook')]
    public function addBook(Request $request, ManagerRegistry $managerRegistry)
    {
        $book = new Book();
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);
        $book->setpublished(true);
        if ($form->isSubmitted()) {
            $em = $managerRegistry->getManager();
            $nbBooks=$book->getAuthor()->getnbrBooks();

            $em->persist($book);
            $em->flush();
            return new Response("done");
        }
        return $this->render("book/addbook.html.twig", array("formulaireBook" => $form->createView()));
    }

    #[Route('/bookList', name: 'book_list')]
    public function list(BookRepository $repository)
    {
        $book= $repository->findAll();
        return $this->render("book/list.html.twig",
            array("tabBooks"=>$book));
    }

    #[Route('/editbook/{ref}', name: 'edit_book')]
    public function edit(Request $request, ManagerRegistry $managerRegistry,BookRepository $repository,$ref)
    {
        $book = $repository->find($ref);
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $em = $managerRegistry->getManager();
            $em->flush();
            return new Response("Book modified");
        }
        return $this->render("book/edit.html.twig", array("formulaireBook" => $form->createView()));
    }
    #[Route('/deletebook/{ref}', name: 'delete_book')]
    public function delete($ref,BookRepository $repository,ManagerRegistry $managerRegistry)
    {
        $book= $repository->find($ref);
        $em= $managerRegistry->getManager();
        $em->remove($book);
        $em->flush();
        return new Response("Book deleted");
    }
    #[Route('/showbook/{ref}', name: 'show_book')]
    public function show($ref,BookRepository $repository){
        $book= $repository->find($ref);
        return $this->render('book/show.html.twig',array('thisBook'=>$book));
    }
}

templates/book/addbook.html.twig
<h1> Add a Book </h1>
{{form(formulaireBook)}}

templates/book/edit.html.twig
<h1> Edit a Book </h1>
{{form(formulaireBook)}}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/HP/FirstProject/src/Controller/BookController.php'|file_link(0) }}">src/Controller/BookController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/HP/FirstProject/templates/book/index.html.twig'|file_link(0) }}">templates/book/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/book/list.html.twig
<table border="1">
    <tr>
        <td>Ref</td>
        <td>title</td>
        <td>published</td>
        <td>publication_date</td>
        <td>category</td>
        <td>author</td>
    </tr>

    {% for book in tabBooks %}
        <tr>
            <td>    {{ book.ref }}
            </td>
            <td>    {{ book.title }}
            </td>
            <td>    {{ book.published }}
            </td>
            <td>    {{ book.PublicationDate | date }}
            </td>
            <td>    {{ book.category }}
            </td>
            <td>    {{ book.author }}
            </td>
            <td>
            <a href="{{path('edit_book',{'ref':book.ref})}}">Edit</a>
            <a href="{{path('delete_book',{'ref':book.ref})}}">Delete</a>
            <a href="{{path('show_book',{'ref':book.ref})}}">Show</a>
            </td>
        </tr>
    {% endfor %}
</table>

templates/book/show.html.twig
<h1>Book</h1>
<h4>Title : {{thisBook.title}}</h4>
<h4>Publication Date : {{thisBook.publicationDate|date('d/m/Y')}}</h4>
<h4>Author : {{thisBook.author.getUsername}}</h4>